### PR TITLE
Curie now supports representation of a default

### PR DESCRIPTION
**Pull request by phillord**
The Curie struct prefix is now Option, to cover when a curie
is a default. It also implements the From trait for String, providing
a stronger guarantee for rendering.

### CODE REVIEW

**Comment by phillord** [comment]
This is quite a big patch because it changes construction of the Curie. I think it could be done in way which has smaller implications, but this is probably the right thing to do.

I've also added string rendering, because there is no way to do this at the moment except via the "debug" trait which seems a bad thing to rely on.

**Comment by waywardmonkeys** [comment]
I'm going to merge this as is ... I think that the allocations incurred in `fmt::Display` due to `String::from` shouldn't be needed, but I'll fix that up. I'll also run `rustfmt`.

**Comment by waywardmonkeys** [comment]
Thanks!

**Comment by waywardmonkeys** [comment]
Published as `0.0.8` with a few updates.

**Comment by phillord** [comment]
Thanks! Need to get used to running `rustfmt` clearly!

**Pull request merged**
